name: Linux Kernel Compilation

on:
  workflow_dispatch:

jobs:
  build-x86:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Linux kernel version
        id: kernel
        run: echo "krel=$(curl -sL "https://www.kernel.org" | grep -A 1 "latest_link" | tail -n +2 | sed 's|.*">||' | sed 's|</a>||')" >> $GITHUB_OUTPUT

      - name: Prep
        run: |
          cd $HOME
          wget "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          tar xf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          rm -rf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
      - name: Compile
        run: |
          cd $HOME
          source <(curl -s "https://raw.githubusercontent.com/dakkshesh07/compiler-bench/main/compiler.list")
          for i in "${!compilers[@]}"; do   ${compilers[$i]}; done
          printf -v compiler_list '%s,' "${compilers[@]}"
          compiler_list=${compiler_list%,}
          cd "linux-${{ steps.kernel.outputs.krel }}"
          wget "https://raw.githubusercontent.com/Neutron-Toolchains/clang-build/main/patches/linux/6.1.6/20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          patch -p1 < "20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          echo Caching kernel source in ram...
          for i in `find -type f`;        do              cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;     done
          echo Starting benchmark...
          hyperfine -w 2 -r 3 -p 'make distclean' \
            -L compiler ${compiler_list} 'PATH="$HOME/toolchains/{compiler}/bin:${PATH}" 
            LD_LIBRARY_PATH="$HOME/toolchains/{compiler}/lib" make distclean defconfig all -j$(nproc --all) LLVM="$HOME/toolchains/{compiler}/bin" LLVM_IAS=1' -c 'make distclean' \
            --export-json x86.json
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          path: ~/linux-${{ steps.kernel.outputs.krel }}/x86.json

  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Linux kernel version
        id: kernel
        run: echo "krel=$(curl -sL "https://www.kernel.org" | grep -A 1 "latest_link" | tail -n +2 | sed 's|.*">||' | sed 's|</a>||')" >> $GITHUB_OUTPUT

      - name: Prep
        run: |
          cd $HOME
          wget "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          tar xf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          rm -rf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
      - name: Compile
        run: |
          cd $HOME
          source <(curl -s "https://raw.githubusercontent.com/dakkshesh07/compiler-bench/main/compiler.list")
          for i in "${!compilers[@]}"; do   ${compilers[$i]}; done
          printf -v compiler_list '%s,' "${compilers[@]}"
          compiler_list=${compiler_list%,}
          cd "linux-${{ steps.kernel.outputs.krel }}"
          wget "https://raw.githubusercontent.com/Neutron-Toolchains/clang-build/main/patches/linux/6.1.6/20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          patch -p1 < "20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          echo Caching kernel source in ram...
          for i in `find -type f`;        do              cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;     done
          echo Starting benchmark...
          hyperfine -w 2 -r 3 -p 'make distclean' \
            -L compiler ${compiler_list} 'PATH="$HOME/toolchains/{compiler}/bin:${PATH}" 
            LD_LIBRARY_PATH="$HOME/toolchains/{compiler}/lib" make distclean defconfig all -j$(nproc --all) ARCH=arm64 LLVM="$HOME/toolchains/{compiler}/bin" LLVM_IAS=1' -c 'make distclean' \
            --export-json arm64.json
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          path: ~/linux-${{ steps.kernel.outputs.krel }}/arm64.json

  build-arm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Linux kernel version
        id: kernel
        run: echo "krel=$(curl -sL "https://www.kernel.org" | grep -A 1 "latest_link" | tail -n +2 | sed 's|.*">||' | sed 's|</a>||')" >> $GITHUB_OUTPUT

      - name: Prep
        run: |
          cd $HOME
          wget "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          tar xf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
          rm -rf "linux-${{ steps.kernel.outputs.krel }}.tar.xz"
      - name: Compile
        run: |
          cd $HOME
          source <(curl -s "https://raw.githubusercontent.com/dakkshesh07/compiler-bench/main/compiler.list")
          for i in "${!compilers[@]}"; do   ${compilers[$i]}; done
          printf -v compiler_list '%s,' "${compilers[@]}"
          compiler_list=${compiler_list%,}
          cd "linux-${{ steps.kernel.outputs.krel }}"
          wget "https://raw.githubusercontent.com/Neutron-Toolchains/clang-build/main/patches/linux/6.1.6/20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          patch -p1 < "20221118_yingchi_x86_fpu_Use__Alignof_to_avoid_undefined_behavior_in_TYPE_ALIGN.patch"
          echo Caching kernel source in ram...
          for i in `find -type f`;        do              cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;             cat $i > /dev/null;     done
          echo Starting benchmark...
          hyperfine -w 2 -r 3 -p 'make distclean' \
            -L compiler ${compiler_list} 'PATH="$HOME/toolchains/{compiler}/bin:${PATH}" 
            LD_LIBRARY_PATH="$HOME/toolchains/{compiler}/lib" make distclean defconfig all -j$(nproc --all) ARCH=arm LLVM="$HOME/toolchains/{compiler}/bin" LLVM_IAS=1' -c 'make distclean' \
            --export-json arm.json
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          path: ~/linux-${{ steps.kernel.outputs.krel }}/arm.json
